name: Setup glslang

inputs:
  os:
    required: true

runs:
  using: composite
  steps:
    - name: Install glslang (Linux/Windows)
      if: runner.os != 'macOS'
      shell: pwsh
      run: |
        mkdir glslang
        cd glslang
        if ("${{ runner.os }}" -eq "Windows") {
          Invoke-WebRequest -Uri https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip -OutFile glslang-master.zip
          }
        elseif ("${{ runner.os }}" -eq "Linux") {
          Invoke-WebRequest -Uri https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip -OutFile glslang-master.zip
          }
        Expand-Archive -Path glslang-master.zip -DestinationPath ./
        cd ../
        echo "${{ github.workspace }}/glslang/bin" >> $env:GITHUB_PATH

    - name: Install glslang (macOS)
      if: runner.os == 'macOS'
      run: brew install glslang
