configuration:
  - release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      GENERATOR: "Ninja"
      VCVARSALL: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build/vcvarsall.bat"
      PLATFORM:  x64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  # used as mingw
      GENERATOR: "Ninja"
      CC:        C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gcc.exe
      CXX:       C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      GENERATOR: ""

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
      GENERATOR: "Ninja"

install:
- ps: >-
    $VK_SDK = '1.4.304.0'

    if($IsLinux) {
      sudo apt-get update
      sudo apt-get --yes install libvulkan-dev libasound2-dev libx11-dev libxcursor-dev
      # Vulkan SDK
      $env:VULKAN_SDK      = "$env:APPVEYOR_BUILD_FOLDER/VulkanSDK/$VK_SDK/x86_64"
      $env:VK_LAYER_PATH   = "$env:VULKAN_SDK/etc/vulkan/explicit_layers.d"
      $env:LD_LIBRARY_PATH = "$env:VULKAN_SDK/lib"
      Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/$VK_SDK/linux/vulkansdk-linux-x86_64-$VK_SDK.tar.xz -OutFile VulkanSDK.tar.xz
      mkdir VulkanSDK
      tar -xJf VulkanSDK.tar.xz -C ./VulkanSDK
      }

    if($IsWindows) {
      # Vulkan SDK
      $env:VULKAN_SDK = "C:/VulkanSDK/$VK_SDK"
      Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/$VK_SDK/windows/VulkanSDK-$VK_SDK-Installer.exe -OutFile VulkanSDK.exe
      ./VulkanSDK.exe --accept-licenses --default-answer --confirm-command install
      }

    if($IsLinux) {
      # GLSL compiller
      mkdir glslang
      cd glslang
      Invoke-WebRequest -Uri https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip -OutFile glslang-master.zip
      7z x glslang-master.zip
      cd ..
      $env:PATH += ":$env:APPVEYOR_BUILD_FOLDER/glslang/bin"
      }

    if($IsWindows) {
      mkdir glslang
      cd glslang
      Invoke-WebRequest -Uri https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip -OutFile glslang-master.zip
      7z x glslang-master.zip
      cd ..
      $env:PATH += ";$env:APPVEYOR_BUILD_FOLDER\glslang\bin"
      }

    if($IsMacOS) {
      brew install glslang
      }

before_build:
- ps: >-
    git submodule -q update --init --recursive

    mkdir build

    if($IsWindows) {
      $env:PATH += ";C:/msys64/mingw64/bin;C:/Qt/Tools/QtCreator/bin"
      }

build_script:
  - cmake --version
  - cmd: if "%GENERATOR%" == "MinGW Makefiles" gcc --version
  - cmd: if "%GENERATOR%" == "MinGW Makefiles" g++ --version

  - cd Tests/tests
  - cmd: if NOT "%VCVARSALL%" == "" call "%VCVARSALL%" %PLATFORM%
  - cmd: cmake -H. -B../../build -G "%GENERATOR%" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_SH=CMAKE_SH-NOTFOUND
  - sh:  cmake -H. -B../../build                  -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
  #- ps:  $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmake --build ../../build --target TempestTests

test_script:
- ps: >-
    if($IsWindows) {
      $env:PATH += ";C:/msys64/mingw64/bin;C:/Qt/Tools/QtCreator/bin"
      cd $env:APPVEYOR_BUILD_FOLDER\build\testsuite
      # Download vulkan-1.dll
      $VULKAN_RUNTIME_URL = "https://sdk.lunarg.com/sdk/download/$VK_SDK/windows/vulkan-runtime-components.zip?Human=true"
      Start-FileDownload "$VULKAN_RUNTIME_URL" -FileName "vulkan-runtime.zip"
      7z e "vulkan-runtime.zip" "*/x64"
      if("Visual Studio 16 2019" -eq $env:GENERATOR) {
        cp ".\Debug\TempestTests.exe" "TempestTests.exe";
        cp ".\Debug\Tempest.dll" "Tempest.dll";
        }
      ./TempestTests.exe
      # $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
    if($IsLinux) {
      printenv
      cd $env:APPVEYOR_BUILD_FOLDER/build/testsuite
      ./TempestTests
      }
    if($IsMacOS) {
      printenv
      cd $env:APPVEYOR_BUILD_FOLDER/build/testsuite
      lldb -o run -o quit -- ./TempestTests
      }

artifacts:
  - path: build/tempest/tempest.zip
    name: archive

deploy:
  release: tempest-win32-v$(appveyor_build_version)
  description: 'no release description'
  provider: GitHub
  auth_token:
    secure: 9IgewrZL7gvgL+SofpEkJ6ERQDcsfVBHMUv5qhkj00wfELRiYVJtudQzPVDFE8cq
  artifact: archive
  draft: true
  force_update: true
  prerelease: true
  on:
    branch: master                # release from master branch only
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    appveyor_repo_tag: true       # deploy on tag push only
