#version 440

#extension GL_EXT_nonuniform_qualifier : require

layout(binding = 0, rgba8) uniform writeonly image2D ret;
layout(binding = 1) uniform texture2D tex[2];
layout(binding = 2) uniform sampler   smp;

void main() {
  ivec2 index = ivec2(gl_GlobalInvocationID.xy);
  vec2  uv    = vec2(index.xy) / vec2(imageSize(ret));

  uint  dynIndex = ((index.x/10+index.y/10)%2);
  vec4  color    = texture(sampler2D(tex[nonuniformEXT(dynIndex)],smp), uv);
  imageStore(ret, index, color);
  }
