#version 440

#extension GL_EXT_nonuniform_qualifier : require

layout(binding = 0, std140) readonly buffer Input {
  vec4 val[];
  } ssbo[3];
layout(binding = 1, rgba8) uniform writeonly image2D ret;

void main() {
  ivec2 index = ivec2(gl_GlobalInvocationID.xy);
  vec2  uv    = vec2(index.xy) / vec2(imageSize(ret));

  uint  dynIndex = ((index.x/10+index.y/10)%3);
  vec4  color    = ssbo[nonuniformEXT(dynIndex)].val[0];
  imageStore(ret, index, color);
  }
